on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

name: Continuous Integration

jobs:
  check:
    name: Check compilation
    if: github.event_name != 'push'
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gtk3
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y libgtk-3-dev
      - name: Setup toolchain
        run: rustup show
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        run: rustup show
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gtk3
        run: sudo apt-get install -y libgtk-3-dev
      - name: Setup toolchain
        run: rustup show
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
