on: [push, workflow_dispatch]

name: Build Artifacts

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
            - platform: ubuntu-latest
              name: x86_64-linux
              target: target/release/osu-link
            - platform: macos-latest
              name: x86_64-macos
              target: target/release/osu-link
            - platform: windows-latest
              name: x86_64-win
              target: target/release/osu-link.exe

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gtk3
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y libgtk-3-dev
      - name: Setup toolchain
        run: rustup show
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: osu-link.${{ matrix.name }}
          path: ${{ matrix.target }}
