on: [push, workflow_dispatch]

name: Build Artifacts

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        run: rustup show
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
